// NOAH Exploration v2: story-faithful adapter for the original prototype.
(function(){
const w=window;
const EX={map:'fountain',x:50,y:72,locked:false,adv:null,ai:0,stage:'child',stallDone:false,babelReached:false};
const E=id=>document.getElementById(id);
function open(map='fountain',x=50,y=72){EX.map=map;EX.x=x;EX.y=y;EX.locked=false;render();E('exploreOverlay').classList.add('active');E('statusBar').classList.add('visible');E('invBar').classList.add('visible');player(x,y);close();if(w.updateInv)w.updateInv()}
function player(x,y){EX.x=x;EX.y=y;E('explorePlayer').style.left=x+'%';E('explorePlayer').style.top=y+'%'}
const maps={
 fountain:{label:'HELIOPOLIS / 噴水公園',bg:'fountain',spots:[['child',31,48,'子ども','○',scene2],['stall',86,58,'屋台街','▣',()=>{if(EX.stage!=='child')go('stall',22,72)}]]},
 stall:{label:'HELIOPOLIS / 屋台街',bg:'stall',spots:[['stall',52,48,'屋台','▣',scene3],['road',88,24,'北の大通り','↑',()=>{if(EX.stallDone)scene3c()}],['fountain',15,78,'噴水広場へ','←',()=>go('fountain',84,70)]]},
 district:{label:'HELIOPOLIS / 大通り',bg:'district',spots:[['tower',51,34,'白い塔','◇',()=>say([{sp:'',tx:'白い塔が、少しずつ大きくなる。',sub:'人が増えてくる。みな、どこかへ向かっている。'}])],['passerby',27,54,'通行人','○',()=>say([{sp:'通行人（すれ違いざまに）',tx:'「……初めてか。案内所に行くといい」',sub:''}])],['office',77,57,'総合案内所','▣',()=>{if(EX.stage==='office')scene5()}],['south',10,82,'噴水公園へ戻る','↓',()=>go('fountain')]]},
 interior:{label:'HELIOPOLIS / 総合案内所',bg:'interior',spots:[['reception',31,43,'受付','○',()=>{if(EX.stage==='office'||EX.stage==='diagnose'||EX.stage==='omon')scene5()}],['terminal',68,42,'端末','▣',()=>say([{sp:'',tx:'案内所の端末には、見慣れない記録が並んでいる。',sub:'「EgoSys：行為は世界に残る」'}])],['back',79,70,'受付の奥','!',()=>{if(EX.stage==='omon')scene10b()}],['exit',12,84,'外へ','←',()=>go('district')]]},
 detour:{label:'HELIOPOLIS / BABEL第一階層',bg:'detour',spots:[['babel',52,39,'BABEL','◇',babel],['forward',88,82,'先へ','→',()=>{if(EX.babelReached)w.showEnding()}]]}
};
function render(){const m=maps[EX.map];E('exploreBg').style.backgroundImage=`url(${w.MAPS[m.bg]})`;E('exploreLocation').textContent=m.label;const f=E('exploreField');f.querySelectorAll('.explore-hotspot').forEach(n=>n.remove());m.spots.forEach(([id,x,y,label,icon,fn])=>{const b=document.createElement('button');b.className='explore-hotspot';b.dataset.id=id;b.style.left=x+'%';b.style.top=y+'%';b.innerHTML=`${icon}<span class="hot-label">${label}</span>`;b.onclick=e=>{e.stopPropagation();move(x,y,fn)};f.appendChild(b)})}
function move(x,y,fn){if(EX.locked)return;EX.locked=true;E('exploreCross').style.left=x+'%';E('exploreCross').style.top=y+'%';E('exploreCross').classList.add('visible');player(x,y);setTimeout(()=>{EX.locked=false;E('exploreCross').classList.remove('visible');fn&&fn()},480)}
function field(e){if(EX.locked||E('exploreAdv').classList.contains('visible')||E('exploreChoices').classList.contains('visible'))return;const r=E('exploreField').getBoundingClientRect();move(Math.max(5,Math.min(95,(e.clientX-r.left)/r.width*100)),Math.max(8,Math.min(90,(e.clientY-r.top)/r.height*100)))}
E('exploreField').addEventListener('click',field);
function close(){E('exploreAdv').classList.remove('visible');E('exploreChoices').classList.remove('visible');E('exploreChoices').innerHTML='';EX.adv=null}
function say(lines,next){EX.adv={lines,next};EX.ai=0;E('exploreChoices').classList.remove('visible');E('exploreAdv').classList.add('visible');line()}
function line(){const s=EX.adv.lines[EX.ai];E('exploreAdvSpeaker').textContent=s.sp||'';E('exploreAdvText').textContent=s.tx||'';E('exploreAdvSub').textContent=s.sub||'';E('exploreAdvTap').textContent=EX.ai<EX.adv.lines.length-1?'TAP':'TAP / NEXT'}
E('exploreAdv').addEventListener('click',e=>{e.stopPropagation();if(EX.ai<EX.adv.lines.length-1){EX.ai++;line()}else{const n=EX.adv.next;close();n&&n()}});
function choices(a){E('exploreAdv').classList.remove('visible');const c=E('exploreChoices');c.innerHTML='';c.classList.add('visible');a.forEach(([t,fn,h])=>{const b=document.createElement('button');b.className='explore-choice';b.innerHTML=t+(h?`<small>${h}</small>`:'');b.onclick=e=>{e.stopPropagation();close();fn()};c.appendChild(b)})}
function go(m,x=50,y=72){close();open(m,x,y)}
function childDone(){if(w.G.phaseTriggered){w.addEcoa(30);go('stall',22,72)}else w.triggerPhase(()=>go('stall',22,72))}
function scene2(){say([{sp:'子ども',tx:'「あれ……どこ行った？」',sub:'壊れた玩具の部品が、地面に落ちている。'}],()=>choices([['声をかける',s2talk],['周囲を探す',s2look],['工具で修理する',s2repair,'持っているものを使う'],['足跡を追う',s2foot,'地面に何かの跡がある'],['今は立ち去る',s2leave]]))}
function s2talk(){say([{sp:'',tx:'あなたは子どもに声をかけた。',sub:'「大丈夫。何をなくしたの？」'},{sp:'子ども',tx:'「これの、もう片方。さっきまであったのに」',sub:'壊れた玩具を見せる。'},{sp:'',tx:'その時、噴水の水面がかすかに揺れた。',sub:'誰かの声が、耳の奥で小さく響く。「……見て。花壇の近く」'}],()=>choices([['花壇を探す',s2flower],['子どもの隣に座る',s2sit]]))}
function s2look(){say([{sp:'',tx:'あなたは周囲を見渡した。',sub:'花壇。ベンチ。屋台の木箱。噴水の縁。'},{sp:'',tx:'風が吹いた時、花壇の奥で小さな金属片が光った。',sub:''}],s2pick)}
function s2repair(){w.G.helpedChild=true;w.G.hasCrystal=true;w.updateInv();say([{sp:'',tx:'あなたは持っていた工具を取り出した。',sub:'壊れた玩具の構造を見る。単純な留め具の外れだ。'},{sp:'',tx:'数秒で、玩具は元の形に戻った。',sub:''},{sp:'子ども',tx:'「すごい！」',sub:'両目が丸くなった。'},{sp:'子ども',tx:'「直せるの？ なんで？」',sub:''}],()=>{w.flashScreen();w.showEgoSys('あなたの技術が記録されました。この街は、あなたの手の使い方を覚えています。',7000);childDone()})}
function s2foot(){w.G.helpedChild=true;w.G.hasCrystal=true;w.updateInv();say([{sp:'',tx:'地面に、小さな足跡が続いている。',sub:'人のものではない。四本足。小さな動物だ。'},{sp:'',tx:'足跡は、噴水の裏の茂みへと続いていた。',sub:''},{sp:'',tx:'茂みの中に、一匹の犬がいた。',sub:'口に、玩具の欠片をくわえている。'},{sp:'子ども',tx:'「あっ、あいつ！」',sub:'駆け寄って、玩具を取り返す。犬は少し不満そうだ。'}],()=>{w.flashScreen();w.showEgoSys('あなたの観察が記録されました。この街は、あなたの目の動きを覚えています。',7000);childDone()})}
function s2leave(){w.G.leftChild=true;say([{sp:'',tx:'あなたは、その場を離れようとした。',sub:'子どもの声が背中に残る。'},{sp:'',tx:'けれど、誰もあなたを責めない。',sub:'この世界は、あなたの選ばなかった行動も、静かに記録している。'}],()=>{w.showEgoSys('選択が記録されました。世界は記憶を持ちます。',6000);setTimeout(()=>go('stall',22,72),800)})}
function s2flower(){w.G.helpedChild=true;w.G.hasCrystal=true;w.updateInv();say([{sp:'',tx:'花壇の影に半分だけ埋もれた玩具の片割れが見えた。',sub:'土に濡れ、少しだけ色がくすんでいる。'},{sp:'',tx:'拾い上げた瞬間、軽い共鳴のような感覚が指先に走る。',sub:'この世界では、失われたものは完全には"消えない"。ただ、少しだけ場所を変える。'},{sp:'子ども',tx:'「それ……！」',sub:'両手で強く抱きしめた。'},{sp:'子ども',tx:'「ありがとう！」',sub:'その瞬間、噴水の音が一度だけ澄んで聞こえた。'}],()=>{w.flashScreen();w.showEgoSys('あなたの行為が記録されました。この街は、あなたがここにいたことを覚えています。',7000);childDone()})}
function s2sit(){say([{sp:'',tx:'あなたは噴水の縁に腰を下ろし、子どもの隣に座る。',sub:'しばらく、何も言わない。'},{sp:'',tx:'「いつ、最後に見た？」',sub:'子どもは少し考え、ぽつりと答える。'},{sp:'子ども',tx:'「走ってたとき……たぶん、そのへん」',sub:'視線を上げると、空間の"記憶の流れ"がわずかに見える。'},{sp:'',tx:'「一緒に探そう」',sub:'子どもが小さくうなずいた。'}],s2fountain)}
function s2fountain(){w.G.helpedChild=true;w.G.hasCrystal=true;w.updateInv();say([{sp:'',tx:'あなたは噴水の周囲を歩く。',sub:'視線ではなく、"流れ"を追う。'},{sp:'',tx:'その一つが、ある一点で途切れていた。',sub:'噴水の縁の内側。流れが一瞬だけ跳ねた場所。'},{sp:'',tx:'手を伸ばし、濡れた石の隙間に指を差し込む。',sub:'冷たい感触。小さな玩具の片割れが、縁の影に引っかかっていた。'},{sp:'子ども',tx:'「……どうして分かったの？」',sub:'答える前に、ポケットの中で小さな光が鳴った。'}],()=>{w.flashScreen();w.showEgoSys('深く感知しました。この世界はあなたの方法を覚えています。',6000);childDone()})}
function s2pick(){w.G.helpedChild=true;w.G.hasCrystal=true;w.updateInv();say([{sp:'',tx:'花壇の奥に、玩具の欠けた部品が落ちていた。',sub:''},{sp:'子ども',tx:'「ありがとう！」',sub:'子どもの顔がぱっと明るくなる。その瞬間、あなたの手の中で小さな光が鳴った。'}],()=>{w.flashScreen();w.showEgoSys('あなたの行為が記録されました。この街は、あなたがここにいたことを覚えています。',7000);childDone()})}
function scene3(){w.G.hasBread=true;w.updateInv();let i=0;const L=[['店主','「……目が醒めたばかりか。」',''],['店主','「祝いだ。最初は皆そうする。」','パンを渡す。'],['店主','「食っときな。次からはエコアが要る。」',''],['店主','「ちょうどいい。袋落とした奴がいる。」','足元に、布の袋が落ちている。']];(function n(){if(i<L.length){const a=L[i++];say([{sp:a[0],tx:a[1],sub:a[2]}],n)}else choices([['拾って渡す',pickBag,'落とし主がそこにいる'],['見なかったことにする',ignoreBag]])})()}
function pickBag(){say([{sp:'落とし主',tx:'「ありがとう。助かったよ。」',sub:''}],()=>{w.flashScreen();w.showEgoSys('あなたの行為が記録されました。世界はあなたを覚えています。',6000);EX.stallDone=true;if(w.G.phaseTriggered){w.addEcoa(30);setTimeout(scene3c,1200)}else w.triggerPhase(scene3c)})}
function ignoreBag(){say([{sp:'',tx:'袋はそのままにした。',sub:'この世界は、あなたの選ばなかった行動も、静かに記録している。'}],()=>{EX.stallDone=true;w.showEgoSys('選択が記録されました。',5000);setTimeout(scene3c,1600)})}
function scene3c(){say([{sp:'',tx:'屋台を後にした。',sub:'北の大通りへ向かえば、総合案内所はすぐだ。噴水広場には、まだ行っていない場所がある。'}],()=>choices([['噴水広場に寄っていく',scene3b,'何かあるかもしれない'],['案内所へ直行する',scene4]]))}
function scene3b(){go('fountain',84,70);setTimeout(()=>say([{sp:'',tx:'噴水の前に戻ると、水面が淡く光っていた。',sub:'小さな看板がある。「この街では、最初のエコアを噴水に捧げる者がいる」'}],()=>choices([['1エコアを投げる',throwEco,'最初の供物'],['投げない',noEco]])),520)}
function throwEco(){w.G.threwEcoa=true;w.G.ecoa=Math.max(0,w.G.ecoa-1);w.updateInv();w.showEgoSys('この街は、あなたを覚えました。最初の供物が記録されています。',7000);say([{sp:'',tx:'あなたは、エコアを一つ噴水へ投げ入れた。',sub:'水面に触れた瞬間、透明な音が広がる。光の紋様が、水の上に一瞬だけ咲いた。「……見てたよ」'}],()=>choices([['総合案内所へ向かう',scene4]]))}
function noEco(){w.showEgoSys('この場所での選択が記録されました。',5000);say([{sp:'',tx:'あなたは、エコアを投げなかった。',sub:'何も起こらない。けれど、少し歩き出した時、水面がかすかに光った。'}],()=>choices([['総合案内所へ向かう',scene4]]))}
function scene4(){EX.stage='office';go('district',18,78);setTimeout(()=>say([{sp:'',tx:'街の通りを歩き始めた。',sub:'総合案内所は北の大通りにある。白い塔を目印にすれば、方角はわかる。'},{sp:'通行人（すれ違いざまに）',tx:'「……初めてか。案内所に行くといい」',sub:''},{sp:'',tx:'白い塔が、少しずつ大きくなる。',sub:'人が増えてくる。みな、どこかへ向かっている。'}],()=>choices([['総合案内所へ向かう',scene5]])),520)}
function scene5(){EX.stage='office';go('interior',18,82);setTimeout(()=>say([{sp:'受付NPC',tx:'「あなたは未登録です。」',sub:'「市民登録、または未登録のまま滞在できます。」'}],()=>choices([['適性診断を受ける',diagnose,'情動傾向を調べる'],['保留する',hold,'後からでも受けられる'],['拒否する',refuse,'罰なし。世界は続く']])),520)}
function hold(){EX.stage='omon';say([{sp:'受付NPC',tx:'「分かりました。いつでも受けられます。」',sub:'そのとき——あなたの背後で、何かが揺れた。'}],scene10)}
function refuse(){EX.stage='omon';say([{sp:'受付NPC',tx:'「……そうですか。」',sub:'受付は少し驚いた顔をした。そのとき——空気が変わった。'}],scene10)}
function diagnose(){EX.stage='diagnose';w._dq=0;w._scores={order:0,inquiry:0,flux:0,limit:0};say([{sp:'受付NPC',tx:'「では、いくつか情景をお見せします。」',sub:'「正解はありません。あなたが感じたままに。」'}],diagQ)}
function diagQ(){if(w._dq>=w.DIAG_Q.length){diagResult();return}const q=w.DIAG_Q[w._dq];say([{sp:`Q${w._dq+1} / ${w.DIAG_Q.length}`,tx:q.q,sub:''}],()=>choices(q.opts.map(([t,k])=>[t,()=>{w._scores[k]++;w._dq++;diagQ()}])))}
function diagResult(){const top=Object.entries(w._scores).sort((a,b)=>b[1]-a[1])[0][0],r=w.DIAG_RESULT[top];w.G.diagResult=top;EX.stage='omon';say([{sp:'受付NPC',tx:`「あなたの情動傾向は——${r.name}に近い」`,sub:`推奨：${r.guild}\n${r.desc}`}],()=>{w.showEgoSys(`情動傾向：${r.name}（${r.guild}）として記録されました。`,8000);setTimeout(scene10,1800)})}
function scene10(){EX.stage='omon';go('interior',45,48);let i=0;const L=[['','空間が一瞬だけ変質する。','プレイヤーの背後に影が現れる。影が二重になる。'],['','完全には見えない。そして、消える。',''],['受付NPC（プレイヤーの後ろを見て）','「ああ……」','小さく笑う。'],['受付NPC','「見えるんですね？」','「魂の伴走者——オトモンです。」'],['OTOMON','「……聞こえる？」','少し間。光が揺れる。'],['OTOMON','「えっと……」','少し間。「やっと見つけた」'],['OTOMON','「一緒に行く？」','']];(function n(){if(i<L.length){const a=L[i++];say([{sp:a[0],tx:a[1],sub:a[2]}],n)}else choices([['はい',()=>{EX.stage='omon';scene10b()}],['いいえ',()=>{EX.stage='omon';w.showOtomon('……じゃあ、近くにいる',4000);setTimeout(scene10b,1200)},'「じゃあ近くにいる」→勝手に付いてくる']])})()}
function scene10b(){let i=0;const L=[['','——そのとき。','ロビーの空気が変わった。'],['','低い唸り声。','受付の奥から、小さな炎が見える。'],['受付NPC','「……出た。」','落ち着いた声で言う。「ここには、たまに迷い込んでくるんです」'],['受付NPC','「危なくはないですが——」','少し間。「でも、誰かが相手をしないといけない」'],['OTOMON','「——行こう。」','オトモンが前に出た。']];(function n(){if(i<L.length){const a=L[i++];say([{sp:a[0],tx:a[1],sub:a[2]}],n)}else{E('exploreOverlay').classList.remove('active');w.startBattle()}})()}
function scene11(){EX.babelReached=false;go('detour',18,72);let i=0;const L=[['OTOMON','「こっちだよ、たぶん」','自信満々に進む。明らかに違う方向。'],['','……どんどん遠ざかっていく、白い塔。','プレイヤーが立ち止まると、オトモンが振り返る。'],['OTOMON','「あれ？」',''],['OTOMON','「ごめん、こっちの方が楽しそうだったから」','悪びれない。でも、少しだけ耳が下がった。'],['','——BABEL第一階層に到達した。','遠回りしたのに、なぜかここに来た。そういう場所なのかもしれない。']];(function n(){if(i<L.length){const a=L[i++];say([{sp:a[0],tx:a[1],sub:a[2]}],n)}else{close();render();player(18,72)}})()}
function babel(){say([{sp:'',tx:'——BABEL第一階層に到達した。',sub:'遠回りしたのに、なぜかここに来た。そういう場所なのかもしれない。'}],()=>{w.G.tookDetour=true;EX.babelReached=true;player(52,72)})}
w.goScene2=()=>open('fountain',50,72);w.goScene3=()=>open('stall',22,72);w.goScene3c=scene3c;w.goScene4=scene4;w.goScene5=scene5;w.goScene10=scene10;w.goScene10b=scene10b;w.goScene11=scene11;
const oldRestart=w.restartAll;w.restartAll=function(){EX.map='fountain';EX.x=50;EX.y=72;EX.locked=false;EX.adv=null;EX.ai=0;EX.stage='child';EX.stallDone=false;EX.babelReached=false;E('exploreOverlay').classList.remove('active');oldRestart&&oldRestart()};
})();
